---
title: "USMAPAO"
author: "D/Math LTC Clark, MAJ Turner, CPT Adams"
date: "November 9, 2018"
output: 
  html_document:
    theme: united
    highlight: tango
    toc: true
    toc_depth: 2
    toc_float: true
    smooth_scroll: TRUE
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
```

# Overview

The following analysis is provided to the USMA PAO on behalf of the CDAS in the Department of MAthematical Sciences.  The purpose is to gain insight into the social media landscape surrounding the the United States Military Academy at West Point.

----

# Download Most Recent Tweets

```{r gettweets, echo=FALSE}
library(shiny)
ui <- fluidPage(
  tags$h3("Functionality Currently Not Working"),
  tags$head(tags$script(src = "message-handler.js")),
  actionButton("do", "Update Tweets")
)

server <- function(input, output, session) {
  observeEvent(input$do, {
    session$sendCustomMessage(type = 'testmessage',
      message = 'Thank you for clicking')
  })
  observeEvent(input$do, {
    data = tibble(x=rnorm(100),y=rnorm(100))
    write.csv(data,"testing.csv")
  })
}

shinyApp(ui = ui, server = server, options = list(height=100))

```

----

```{r include=FALSE}
library(tidyverse)
library(tidytext)
library(lubridate)
added = read_csv("PAOTweets.csv")

textcleaned = added %>%
  unnest_tokens(word, text)

cleanedarticle = anti_join(textcleaned,stop_words, by = "word") %>% select(line,word,screenname,time,followerscount,favoritescount)

mintime = min(cleanedarticle$time)
```

----

# Sentiment by Day

The Plot tab below shows the number of words with both positive and negative sentiment by day.

The table tab below shows the words with sentiment by user, time, follower count, and favorite count.  


```{r panels, echo=FALSE}
library(shiny)
ui <- fluidPage(
  dateRangeInput('dateRange',
    label = 'Please use the filter below to narrow your search criteria between dates of interest.',
    start = mintime,
    end = Sys.Date()),
  tabsetPanel(type = "tabs",
              tabPanel("Plot", plotOutput("sentovertime")),
              tabPanel("Tweets", dataTableOutput("tweettable")
   )
  )
)
server <- function(input, output) {
   
  dataset = reactive({
    filtered = cleanedarticle %>%
    full_join(get_sentiments("nrc"), by = "word") %>%
    # select(-c(location,lat,lng,coords_coords,bbox_coords,geo_coords)) %>%
    filter(complete.cases(.)) %>%
    filter(sentiment == "positive" | sentiment == "negative") %>%
    mutate(time = floor_date(time, unit = "day")) %>%
    mutate(dayofweek = weekdays(time)) %>%
    filter(time <= input$dateRange[2]) %>%
    filter(time >= input$dateRange[1])
    return(filtered)
  })
  
  output$sentovertime = renderPlot({
    ggplot(dataset(), aes(sentiment, fill = sentiment)) +
    geom_bar() +
    facet_wrap(time ~ dayofweek, ncol = 7)
  })
  
  output$text = renderText({
    this = as.character(input$dateRange)
    this = this[2]
    return(this)
  })

  output$tweettable = renderDataTable({
    return(dataset())
  })
  
}

shinyApp(ui = ui, server = server, options = list(height=600))

```

----

# Tweets and Twitter Users of Most Influence

```{r influentialtweets, echo=FALSE}
library(shiny)
ui <- fluidPage(
  # dateInput('dateRange',
  #   label = 'Select a Date of Interest',
  #   value = today(),
  #   min =  mintime,
  #   max = Sys.Date()
  # ),
    dateRangeInput('dateRange',
    label = 'Please use the filter below to narrow your search criteria between dates of interest.',
    start = mintime,
    end = Sys.Date()
  ),
  
    tabsetPanel(type = "tabs",
              tabPanel("Influential Users", 
                       radioButtons("sent","Sentiment of Interest:",
                         choices = c("Positive" = "positive","Negative" = "negative")
                         ),
                       dataTableOutput("tweettable")), 
              tabPanel("Full Tweets", 
                       tags$h3("Tweets Not Filtered By Sentiment"),
                       dataTableOutput("tweettable2"))

)
)
  

server <- function(input, output) {
   
  dataset = reactive({
    filtered = 
      cleanedarticle %>%
  full_join(get_sentiments("nrc"), by = "word") %>%
  # select(-c(location,lat,lng,coords_coords,bbox_coords,geo_coords)) %>%
  filter(complete.cases(.)) %>%
  filter(sentiment=="positive" | sentiment == "negative") %>%
  mutate(time = floor_date(time, unit = "day")) %>%
  mutate(dayofweek = weekdays(time)) %>%
  # filter(as.character(time)==input$dateRange) %>%
  filter(time <= input$dateRange[2]) %>%
  filter(time >= input$dateRange[1]) %>%
  arrange(desc(followerscount)) %>%
  group_by(screenname,sentiment) %>%
  mutate(total = n()) %>%
  distinct(screenname,sentiment, followerscount,favoritescount,total) %>%
  filter(sentiment==input$sent) %>%
  group_by(screenname) %>%
  summarise(FollowersCount = max(followerscount), FavoritesCount = max(favoritescount), Total = sum(total)) %>%
  arrange(desc(FavoritesCount))
    return(filtered)
  })
  

  output$tweettable = renderDataTable(dataset(),{
   options = list(pageLength = 10)
  })
 
    dataset2 = reactive({
    filtered = added %>%
    mutate(time = floor_date(time, unit = "day")) %>%
    mutate(dayofweek = weekdays(time)) %>%
    filter(time <= input$dateRange[2]) %>%
    filter(time >= input$dateRange[1]) %>%
      select(screenname, text, time)
    return(filtered)
  })
  

  output$tweettable2 = renderDataTable(dataset2(),{
   options = list(pageLength = 10)
  })
  
   
}

shinyApp(ui = ui, server = server, options = list(height=1200))

```

----

# Social Heartbeat

```{r singletweets, echo=FALSE}
library(shiny)
ui <- fluidPage(
  radioButtons("option","Plot Type:",
                         choices = c("Ridged" = "riged","Smooth" = "smooth")
                         ),
  plotOutput("heartbeat")
)


server <- function(input, output) {

  dataset = reactive({
filtered =  cleanedarticle %>%
    full_join(get_sentiments("nrc"), by = "word") %>%
    filter(complete.cases(.)) %>%
    filter(sentiment == "positive" | sentiment == "negative") %>%
    mutate(time = floor_date(time, unit = "day")) %>%
    mutate(score = ifelse(sentiment == "positive", 1, -1)) %>%
    group_by(time) %>%
    summarise(dayscore = sum(score) / sum(abs(score))) 
      return(filtered)
  })
  

  output$heartbeat = renderPlot({
    if (input$option == "riged") {
    dataset() %>%
    ggplot(aes(time, dayscore, color = dayscore)) +
    geom_line() +
    # geom_smooth() +
    theme(legend.position = "none") +
    labs(title = "Reputation Heartbeat", x = "Date", y = "Sentiment Score") +
    ylim(-1,1)
    } else if (input$option == "smooth") {
    dataset() %>%
    ggplot(aes(time, dayscore, color = dayscore)) +
    geom_smooth() +
    theme(legend.position = "none") +
    labs(title = "Reputation Heartbeat", x = "Date", y = "Sentiment Score") +
    ylim(-1,1)
    }
  })
  
}

shinyApp(ui = ui, server = server, options = list(height=800))

```

----
